SELECT DEPARTMENT_ID, MIN(SALARY)
    FROM EMPLOYEES
    GROUP BY DEPARTMENT_ID
    HAVING MIN(SALARY) > (SELECT MIN(SALARY)
                            FROM EMPLOYEES
                            WHERE DEPARTMENT_ID = 100);

SELECT E.FIRST_NAME || ' ' || E.LAST_NAME AS "성명", E.JOB, D.DEPARTMENT_ID,D.LOCATION_ID
FROM EMPLOYEES E JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE E.JOB_ID = 'SA_MAN';

SELECT E.FIRST_NAME || ' ' || E.LAST_NAME AS "성명", E.JOB, D.DEPARTMENT_ID, D.LOCATION_ID
FROM EMPLOYEES E JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE E.JOB_ID = 'SA_MAN';
    
SELECT MANAGER_ID, COUNT(*)
    FROM EMPLOYEES
    GROUP BY MANAGER_ID
    HAVING COUNT(*) IN (SELECT MAX(COUNT(*))
                        FROM EMPLOYEES
                        GROUP BY MANAGER_ID);
                        
SELECT EMPLOYEE_ID, FIRST_NAME, JOB_ID, DEPARTMENT_NAME
    FROM EMPLOYEES E JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
    WHERE (JOB_ID, SALARY) IN (SELECT JOB_ID, MIN(SALARY)
                                FROM EMPLOYEES
                                GROUP BY JOB_ID)
    ORDER BY JOB_ID DESC;      
    
UPDATE EX_EMP
    SET SAL = SAL * 1.1, DEPTNO = 80
        WHERE HIREDATE > (SELECT MIN(HIREDATE)
                            FROM EX_EMP
                            WHERE DEPTNO = 60;
                            
DELETE FROM EX_EMP
    WHERE EMPNO IN (SELECT E.EMPNO FROM EX_EMP E JOIN EX_SALGRADE S
                        ON E.SAL BETWEEN S.LOSAL AND S.HISAL
                        WHERE S.GRADE = 5);
SELECT * FROM EX_EMP;                        